function y = filterr(x)
%FILTERR Filters input x and returns output y.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the DSP System Toolbox 8.3.
%
% Generated on: 22-Sep-2014 16:22:18
%

persistent Hd;

if isempty(Hd)
    
    Fpass = 0.01;   % Passband Frequency
    Fstop = 0.015;  % Stopband Frequency
    Apass = 1;      % Passband Ripple (dB)
    Astop = 60;     % Stopband Attenuation (dB)
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop);
    
    Hd = design(h, 'butter', ...
        'FilterStructure', 'df2tsos', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


% [EOF]
